# Blog settings
#permalink: /blog/:title
permalink: /blog/:title

# My variables
name: Another wandering mind - Thoughts about Life, Society and Me. 
description: Sometimes you have thoughts about you, life or society popping up with no reason. You are not the only one. That's why I'm sharing mines with you HERE. 
url: https://anotherwanderingmind.com
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

gems:
  - jekyll-seo-tag

future: false

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

page_gen:
  - data: books
    name: key
    dir: goto
    extention: html
