# Blog settings
#permalink: /blog/:title
permalink: /blog/:title

# My variables
name: Another Wandering Mind
description: Sometimes your mind wanders. You are not the only one. Mine is another wandering mind. 
url: https://anotherwanderingmind.com
locale: en-US
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

gems:
  - jekyll-seo-tag

future: false

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

page_gen:
  - data: books
    name: key
    dir: goto
    extention: html
